services:
  db:
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=nobuzz
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    volumes:
      - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - POSTGRES_URL=postgres://postgres:docker@db:5432/nobuzz
      - SECRET=e14a88ddedba92a324ff2398a179662858c2bee528a8302c92e3f26b0e7f1085
    depends_on:
      db:
        condition: service_healthy
