-- 2023-11-06T17:02:00-03:00

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "Tarefa" (
  "id" UUID NOT NULL DEFAULT uuid_generate_v4(),
  "titulo" CHARACTER VARYING(50) NOT NULL,
  "descricao" TEXT NOT NULL DEFAULT '',
  "dataCriacao" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "dataAtualizacao" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "dataConclusao" TIMESTAMP WITHOUT TIME ZONE NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS tarefa_datacriacao_idx ON "Tarefa" ("dataCriacao");

-- 2023-11-07T09:20:00-03:00

CREATE OR REPLACE FUNCTION trigger_set_dataatualizacao_to_now()
RETURNS TRIGGER AS $$
BEGIN
  NEW."dataAtualizacao" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER set_dataatualizacao_to_now
BEFORE UPDATE ON "Tarefa"
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_dataatualizacao_to_now();

-- 2023-11-07T11:11:00-03:00

CREATE TABLE IF NOT EXISTS "Usuario" (
  "id" UUID NOT NULL DEFAULT uuid_generate_v4(),
  "email" CHARACTER VARYING(254) NOT NULL,
  "senha" TEXT NOT NULL,
  "dataCriacao" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "dataAtualizacao" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);

CREATE OR REPLACE TRIGGER set_dataatualizacao_to_now
BEFORE UPDATE ON "Usuario"
FOR EACH ROW
EXECUTE PROCEDURE trigger_set_dataatualizacao_to_now();
