-- 2023-11-06T17:02:00-03:00

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS "Tarefa" (
  "id" UUID NOT NULL DEFAULT uuid_generate_v4(),
  "titulo" CHARACTER VARYING(50) NOT NULL,
  "descricao" TEXT NOT NULL DEFAULT '',
  "dataCriacao" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "dataAtualizacao" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "dataConclusao" TIMESTAMP WITHOUT TIME ZONE NULL,
  PRIMARY KEY ("id")
);

CREATE INDEX IF NOT EXISTS tarefa_datacriacao_idx ON "Tarefa" ("dataCriacao");
